- repository: autowarefoundation/autoware
  files:
    - source: .github/dependabot.yaml
    - source: .github/workflows/pre-commit-optional.yaml
    - source: .github/workflows/semantic-pull-request.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .markdown-link-check.json
    - source: .markdownlint.yaml
    - source: .pre-commit-config-optional.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml

- repository: autowarefoundation/autoware_common
  files:
    - source: .github/workflows/pre-commit.yaml

- repository: autowarefoundation/autoware-documentation
  files:
    - source: .github/workflows/deploy-docs.yaml
    - source: .github/workflows/delete-closed-pr-docs.yaml

- repository: autowarefoundation/autoware-github-actions
  files:
    - source: deploy-docs/mkdocs-requirements.txt

- repository: tier4/caret_common
  files:
    - source: .cspell.json
