site_name: Chain-Aware ROS Evaluation Tool (CARET)
theme:
  name: "material"
  palette:
    primary: "indigo"
    accent: "indigo"
  hljs_languages:
    - yaml
    - python
    - c++
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate

extra_css:
  - assets/stylesheets/tier4_color.css
  - https://use.fontawesome.com/releases/v5.15.4/css/all.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

plugins:
  - awesome-pages
  - search

markdown_extensions:
  - admonition
  - attr_list
  - codehilite: { guess_lang: false }
  - fontawesome_markdown
  - footnotes
  - mdx_math
  - mdx_truly_sane_lists: { nested_indent: 2 }
  - mdx_unimoji
  - plantuml_markdown: { server: "http://www.plantuml.com/plantuml", format: svg }
  - pymdownx.arithmatex
  - pymdownx.details
  - plantuml_markdown:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

  - toc: { permalink: "#" }
