name: delete-closed-pr-docs

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  delete-closed-pr-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Delete closed PR docs
        uses: takam5f2/autoware-github-actions/delete-closed-pr-docs@remove-mike-argument-rebase
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
