name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    uses: autowarefoundation/autoware-github-actions/.github/workflows/reusable-pre-commit.yaml@tier4/proposal
    with:
      pre-commit-config: .pre-commit-config.yaml
