name: reusable-spell-check

on:
  workflow_call:
    inputs:
      cspell-json-url:
        required: true
        type: string

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve spell check dictionary
        run: |
          curl -fsSL -o .cspell.json \
            ${{ inputs.cspell-json-url }}

      - name: Run spell check
        uses: streetsidesoftware/cspell-action@v1.3.5
        with:
          config: .cspell.json
