name: reusable-get-docs-version-name

on:
  workflow_call:
    outputs:
      version-name:
        value: ${{ jobs.get-docs-version-name.outputs.version-name }}

jobs:
  get-docs-version-name:
    runs-on: ubuntu-latest
    outputs:
      version-name: ${{ steps.get-docs-version-name.outputs.version-name }}

    steps:
      - name: Set version name (push)
        if: ${{ !github.event.pull_request }}
        run: |
          echo "VERSION_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set version name (pull_request)
        if: ${{ github.event.pull_request }}
        run: |
          echo "VERSION_NAME=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Set output
        id: get-docs-version-name
        run: |
          # Replace invalid character '/' by '-'
          echo ::set-output name=version-name::"${VERSION_NAME/\//-}"

      - name: Show result
        run: |
          echo "self packages: ${{ steps.get-docs-version-name.outputs.version-name }}"
