name: semantic-pull-request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pull-request:
    uses: tier4/CARET_doc/.github/workflows/reusable-semantic-pull-request.yaml@@feature/add-ci
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
