name: spell-check-pr

on:
  pull_request:

jobs:
  spell-check:
    uses: tier4/CARET_doc/.github/workflows/reusable-spell-check.yaml@feature/add-ci
    with:
      cspell-json-url: https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/cspell/.cspell.json
